# lem_in

* Инструменты

** Spacemacs

   Отправной точкой для начала работы в этом замечательном редакторе является хорошее знание =vim='а, однако, =spacemacs= идёт дальше, предоставляя удобную точку входа в возможности IDE через нажатие пробела.
   Пробел - самая большая клавиша на кливиатуре, которую =vim= практически игнорирует, здесь же она используется на полную катушку.
   После долгого и мучительного процесса адаптации, переход на =spacemacs= даёт примерно такой же прирост производительности (и такую же зависимость от нового workflow), что и сам =vim=

** Magit

   Этот плагин (для работы с контролем версий через =git=) наравне с =org-mode=, по праву считается настоящей жумчужиной, если угодно "киллер-фичей" =emacs='а.
   Да, он может подвесить ваш любимый редактор на пару минут, если вы случайно включите в коммит папку с парой мегабайт кода, но возможность вносить правки в очередной коммит *построчно* - такого я раньше не видел.
   Также, благодаря взаимодействию с другими плагинами (такими как =ediff=) удобно организованы другие возможности гита, например слияние веток.

** LSP-mode

   Уважаю Microsoft за подобные проекты. =LSP=, или language service protocol - это сервер (daemon), который крутится у вас на компьютере и предоставляет любому редактору кода (умеющему с ним работать) по запросу такие инструменты, как подсветка синтаксиса, автодополнения, описание функций библиотек, подчёркивание ошибок и т.д. и т.п.
   Легко настраивается в =spacemacs=, работает хорошо, особо не тормозит.

** Thinkpad Yoga

   На протяжении всего проекта, чтобы разобраться в алгоритме или понять, почему что-то работает не так, как надо, мне приходилось от руки рисовать различные схемы.
   Уже давно одним из обязательных требований к моему личному рабочему компьютеру является наличие стилуса и экрана с диджитайзером. Писать на экране стилусом во многом куда удобнее, чем на обычной бумаге (возможность стирать, не портя холст, быстро переключать цвета, толщину линии, возможность перераспределить написанное по листу, сохраненить конспект в облако), так что на сегодняшний день я уже практически отказался от бумаги.
   Среди всех перепробованных мной устройств с описанным функционалом ноутбуки "2 в 1" из серии Thinkpad Yoga оказались самыми лучшими (добровольная реклама).


* Благодарности

  Этот мой общий проект с @fcatina.

  Можно сказать, что у проекта также был свой "кризис-менеджер" - @krvkir. Наличие возможности обратиться к грамотному аналитику при работе над проектом - бесценно.

  Первичный толчок к написанию проекта дал отлично реализованный lem-in @hwolf'а, которого я проверял в Школе 21. Именно от него я изначально узнал в какую сторону копать и что гуглить.

  Также хочу поблагодарить @dbendu за предпроверку проекта и указание на его косяки.


* Статистика

- 4-6 недель активной работы
-

* Эволюция алгоритма

** Ход работы

   Работу над проектом я начал с попытки придумать решение самостоятельно, используя только те подходы, которые мне уже были знакомы по прошлым проектам, в частности бэктрекинговый "Алгоритм Икс", который я успешно применил в =fillit='е.

   Несколько дней я пробовал свести новую задачу к работе с матрицей из нулей и единиц, необходимой для алгоритма Кнута, но потом почувствовал, что если это и получится сделать, такое решение окажется очень ресурсоёмким и в конечном счёте медленным.

   Во время проверки @hwolf'а в Школе 21 я попросил его обозначить мне какие-то ключевые слова, которые нужно было гуглить, чтобы решить эту задачу, и он назвал алгоритм Форда-Фалкерсона - с этого началось моё погружение в теорию графов.

   Первое нормальное объяснение базовых вещей из этой совершенно новой для меня области знаний (поток, матрицы смежности и потоков) я получил от @krvkir, после чего уже активно искал информацию и самостоятельно.

   Очень полезным для меня оказался канал на ютубе за авторством Willian Fiset, где он очень хорошо объясняет теорию графов.

-

## Новое

### Теория графов:

Структура данных "очередь"

Понятие потока

Матрица смежности

Алгоритм Форда-Фалкерсона

Поиск в ширину (BFS)

Алгоритм Эдмондса-Карпа

## Ссылки
